### ISSUE TITLE
ttmediabot kurulum aşaması

### ISSUE THREAD

**Issue by orhanbingul** [gumerov-amir/TTMediaBot#105]
ttmediabot.py --devices yazdığımızda aşağıdaki hatayı alıyorum ne yaptıysam çözemedim sizlerden destek bekliyorum

Traceback (most recent call last):
  File "C:\Users\admin\Documents\TTMediaBot-master (1)\TTMediaBot-master\TTMediaBot.py", line 7, in <module>
    from bot import Bot, app_vars
  File "C:\Users\admin\Documents\TTMediaBot-master (1)\TTMediaBot-master\bot\__init__.py", line 10, in <module>
    from bot import (
  File "C:\Users\admin\Documents\TTMediaBot-master (1)\TTMediaBot-master\bot\TeamTalk\__init__.py", line 15, in <module>
    os.add_dll_directory(os.path.join(app_vars.directory, "TeamTalk_DLL"))
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor: 'C:\\Users\\admin\\Documents\\TTMediaBot-master (1)\\TTMediaBot-master\\TeamTalk_DLL'

**Comment by yukie-nobuharu** [comment]
Did you download the TeamTalkSDK using the ttsdk_downloader.py?
if not, run the ttsdk_downloader.py inside the tools folder.

Yukie Nobuharu

----- Original Message -----
From: orhanbingul ***@***.***>
To: gumerov-amir/TTMediaBot ***@***.***>
Cc: Subscribed ***@***.***>
Date: Sat, 04 Nov 2023 11:42:17 -0700
Subject: [gumerov-amir/TTMediaBot] ttmediabot kurulum asamasi (Issue #105)

**Comment by OzancanKaratas** [comment]
Botun kullandığı TeamTalk kitaplığı eksik. TeamTalk uygulamasının DLL kitaplığını botun kök klasörüne kopyalamalısın.

**Comment by cyrmax** [comment]
Thanks for the interest to the TTMediaBot project.
But in issues please stick to english language only.
The bot developer team is from Russia and unfortunately we do not understand other languages besides english and russian.
