### ISSUE TITLE
Problems with using the YouTube service

### ISSUE THREAD

**Issue by dhtstudios** [gumerov-amir/TTMediaBot#32]
Hello there. I am using the TT Media Bot with Debian 10 Linux, with all python modules successfully installed, video and YTDL-Options disabled. Then, whenever I am trying to play a video using the YouTube service, it gives me this via private message in TT: "'NoneType' object has no atribute 'get'. In the Console Window of the Bot I get an HTTP Error 410, with the description "gone". Could someone help me?

**Comment by DraganRatkovich** [comment]
Hi there, is the computer where you use bot your own machine? Or, you
purchased a server?

**Comment by a11cf0** [comment]
It seems that YouTube is blocked by your hosting provider. We can't do anything with that.

**Comment by dhtstudios** [comment]
Well, I am using a server. And is it a problem with YouTube DL or What? So I can ask my provider to unblock it.

**Comment by DraganRatkovich** [comment]
As one of the dev replyed, Google is blocking it, however, try to contact
provider, maybe problem is from their side.
