### ISSUE TITLE
cant change language

### ISSUE THREAD

**Issue by nunotfc** [gumerov-amir/TTMediaBot#34]
hello,
in config.json or comand cl cant change language.
in config if i change to language "tr" it starts in english, and if i type cl tr says invalid language cl ru also

**Comment by DraganRatkovich** [comment]
make sure to compile locales before changing language, using
compile_locales.py script

**Comment by nunotfc** [comment]
you can close, sorry.

Às 12:48 de 14/09/2021, DraganRatkovich escreveu:
> make sure to compile locales before changing language, using
> compile_locales.py script
>
