### ISSUE TITLE
Problems using pulseaudio

### ISSUE THREAD

**Issue by dhtstudios** [gumerov-amir/TTMediaBot#39]
Hi there,
Whenever I start pulseaudio and load (pacmd load-module module-null-sink) on a non-root-user, it gives me no error but it also don't shows the pulse audio devices. I already reinstalled pulseaudio and libmpv1. Thanks for help.

**Comment by a11cf0** [comment]
By default PulseAudio doesn't allow running as root. You need to pass --system as an option to allow this. However, running it as a normal user is highly recommended. Look at the new systemd unit samples to understand how.
