### ISSUE TITLE
setting 2 ttmediabot

### ISSUE THREAD

**Issue by nunotfc** [gumerov-amir/TTMediaBot#48]
hello, im on linux. how i can set 2 input devices in pulse? i want to set 2 bots to same teamtalk in 2 channels, playing different things. when i make annoter i can, but i ear the oter teamtalk song, and the mine channel song. what can i do? thanks!

**Comment by beqabeqa473** [comment]
You can create a separate user and run bot from there or you can use
docker to spin up isolated containers.

On 11/29/21, Nuno ***@***.***> wrote:
> hello, im on linux. how i can set 2 input devices in pulse? i want to set 2
> bots to same teamtalk in 2 channels, playing different things. when i make
> annoter i can, but i ear the oter teamtalk song, and the mine channel song.
> what can i do? thanks!
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gumerov-amir/TTMediaBot/issues/48


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
