### ISSUE TITLE
problem runnint TTMediaBot on docker

### ISSUE THREAD

**Issue by nunotfc** [gumerov-amir/TTMediaBot#49]
hello,
i'm not so experient in docker, just following readme
i run:
docker build -t ttmediabot .
docker run --rm --name ttmb_1 -dv root/TTMediaBot2:/home/ttbot/data ttmediabot
the folder TTMediaBot2 has 0 files just copied my config.json.
the docker builds, but not runs. just apears some random leters and numbers, but not epaers to run, bot not enter in my server. what i am doing wrong? thanks!

**Comment by nunotfc** [comment]
i got the error, the error i have in docker is:
 PermissionError: [Errno 13] Permission denied: '/home/ttbot/data/TTMediaBot.log'

**Comment by beqabeqa473** [comment]
Try to change owner of data directory to uid=1000 gid=1000

On 11/30/21, Nuno ***@***.***> wrote:
> i got the error, the error i have in docker is:
>  PermissionError: [Errno 13] Permission denied:
> '/home/ttbot/data/TTMediaBot.log'
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gumerov-amir/TTMediaBot/issues/49#issuecomment-982351062


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by nunotfc** [comment]
how i make it, i not undestand anything about docker, hjust using comands provided in readme.
and everytime i'm geting error config file is used anoter instance of bot even running in separate containers
for running in oter container i need to change for example ttmb_1 to ttmb_2?
sorry for all but i'm really terrible at docker

**Comment by nunotfc** [comment]
done, it solved my problem. now, the docker container opens, i see the teamtalk message, the sdk message. but the bot is not in my server
the log is:
WARNING [2021-11-30 09:02:34,573]: Connection failed in TeamTalkThread file: thread.py line 64 function run
ERROR [2021-11-30 09:02:34,573]: Connection error in TeamTalkThread file: thread.py line 80 function run

**Comment by beqabeqa473** [comment]
For first question: on a host machine try to do chown -R 1000:1000 <datadir>

For this second: are you trying to login with localhost?

if yes, then you should add --network host to runable command.

On 11/30/21, Nuno ***@***.***> wrote:
> done, it solved my problem. now, the docker container opens, i see the
> teamtalk message, the sdk message. but the bot is not in my server
> the log is:
> WARNING [2021-11-30 09:02:34,573]: Connection failed in TeamTalkThread file:
> thread.py line 64 function run
> ERROR [2021-11-30 09:02:34,573]: Connection error in TeamTalkThread file:
> thread.py line 80 function run
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/gumerov-amir/TTMediaBot/issues/49#issuecomment-982428072


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by nunotfc** [comment]
solved all, with net=host command. thanks! 
how i can run  multiple containers using same configuration file? i have to create  each folders for  each instances i want to run? because i get config file is used to annoter instance.

**Comment by beqabeqa473** [comment]
it is not possible to run two instances with the same config file.
You should create config per instance.

On 11/30/21, Nuno ***@***.***> wrote:
> solved all, with net=host command. thanks!

> how i can run  multiple containers using same configuration file? i have to
> create  each folders for  each instances i want to run? because i get config
> file is used to annoter instance.

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/gumerov-amir/TTMediaBot/issues/49#issuecomment-982570385


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili
