### ISSUE TITLE
Translation System

### ISSUE THREAD

**Issue by lbk2907** [gumerov-amir/TTMediaBot#51]
Hey all. I have a question here about translation system. May I know how can I get an empty translation string to translate the bot? I have try to use "import from source" method from poedit and it didn't return any string for me to translate. I also have try the CMD method using gettext tools that come with python as well. Same thing happend, nothing has been return for me to translate. May I know the exact way to do it? Thanks.

**Comment by lbk2907** [comment]
May I know, which file will got effected in order to fix this bug? Because
I have my own copy of the bot that I already make changes to it. Thanks.

**Comment by a11cf0** [comment]
tools/compile_locales.py

**Comment by lbk2907** [comment]
Only that file? Because I have make changes in the TeamTalk __init__.py. I
change the default status. I also have totally edit the commands
__init__.py, admin_commands.py and user_commands.py. With the changes, the
config and app_vars.py also effected.

**Comment by lbk2907** [comment]
That's mean I no need to worry about those file accept the compile_local.py
in site the tools folder only. I have edit that file also but just change
the file name for the po and mo file. "translation.py" also not got
effected right? Sorry if I ask to many. Just want to make sure for the
update preparation. Thanks.

**Comment by a11cf0** [comment]
Don't worry. Everything will be fixed.

**Comment by lbk2907** [comment]
Thanks. I hope I can learn many things from this source code. Are you have
telegram or other contact information so that I can send you message if I
have any question to ask about python?

**Comment by a11cf0** [comment]
@lbk2907 https://t.me/a11cf0
