### ISSUE TITLE
TT Media Bot does not Produce sound in Windows Virtual PrivateServer

### ISSUE THREAD

**Issue by SalehAcehUtara** [gumerov-amir/TTMediaBot#53]
happy day everyone.
May goodness always be with us.

Ask for your experience, about TTMediaBot on a Windows VPS.
I've tried to install virtual audio on a windows virtual private server, and I found out the line number using the command python TTMediaBot.py --devices
I followed the instructions carefully and made sure there were no errors Anywhere.
this is the umpteenth try, I'm using Windows Server 2019 (x64) build 17763.1
If so, please experience and answer yes?
Sharing is beautiful!

**Comment by SalehAcehUtara** [comment]
One more thing, I've also deleted the virtual audio driver many times, and reinstalled it

**Comment by lbk2907** [comment]
Which version of Windows VPS that are you using?

**Comment by lbk2907** [comment]
Make sure the Virtual Audio Cable is not muted.

**Comment by SalehAcehUtara** [comment]
Oh yeah, for that, I've also double-checked, and the virtual audio cable isn't silent, it's been activated

**Comment by SalehAcehUtara** [comment]
Device output or input device

**Comment by SalehAcehUtara** [comment]
Oh yes one more thing I forgot to mention. and I'm using a vps version of windows here's one of the details: 

OS Name; Value: Microsoft Windows Server 2019 Datacenter 
Version; Value: 10.0.17763 Build 17763 

System Name; Value: TEDDYSUN 
System Manufacturer; Value: DigitalOcean 
Processor; Value: DO-Regular, 2494 Mhz, 1 Core(s), 1 Logical Processor(s) 
BIOS Version/Date; Value: DigitalOcean 20171212, 12/12/2017

**Comment by lbk2907** [comment]
Check your config then.

**Comment by SalehAcehUtara** [comment]
I've made sure the config is correct, because I Tried it on my laptop produces audio. but in v p s windows, it doesn't do anything. even though I have made sure many times, checked carefully, and confirmed that none of the audio was disabled.






{
    "general": {
        "language": "id",
        "send_channel_messages": true,
        "cache_file_name": "TTMediaBotCache.dat",
        "blocked_commands": [],
        "delete_uploaded_files_after": 300,
        "time_format": "%H:%M",
        "load_event_handlers": false,
        "event_handlers_file_name": "event_handlers.py"
    },
    "sound_devices": {
        "output_device": 18,
        "input_device": 61
    },
    "player": {
        "default_volume": 50,
        "max_volume": 100,
        "volume_fading": true,
        "volume_fading_interval": 0.025,
        "seek_step": 5,
        "player_options": {
            "video": false,
            "ytdl": false
        }
    },
    "teamtalk": {
        "hostname": "139.59.225.197",
        "tcp_port": 1409,
        "udp_port": 1409,
        "encrypted": false,
        "nickname": "Bot_requester",
        "status": "",
        "gender": "n",
        "username": "Audio Player",
        "password": "chicken.mp4",
        "channels": "/",
        "channel_password": "",
        "license_name": "",
        "license_key": "",
        "reconnection_attempts": -1,
        "reconnection_timeout": 10,
        "users": {
            "admins": [
                "Audio Player",
                "mai firdaus",
                "Queen",
                "Sham",
                "123"
            ],
            "banned_users": []
        },
        "default_status": "Send \"start\" to start"
    },
    "services": {
        "available_services": {
            "vk": {
                "tokens": ""
            },
            "yt": {}
        },
        "default_service": "vk"
    },
    "loggers": {
        "logs": true,
        "levels": "INFO",
        "format": "%(levelname)s [%(asctime)s]: %(message)s in %(threadName)s file: %(filename)s line %(lineno)d function %(funcName)s",
        "mode": "FILE",
        "file_name": "TTMediaBot.log",
        "max_file_size": 0,
        "backup_count": 0
    }
}

**Comment by lbk2907** [comment]
Make sure that you read the input device from bottom. Don’t forget that
input device will list two same device. The correct one is the second one,
not the first one. That’s mean, the correct device is the first one from
the bottom.

**Comment by SalehAcehUtara** [comment]
oh, that must be it, I tried to enter from the first of
low part.
that's why on my own windows device, now the problem is only on Windows' Firtual private server which doesn't produce audio.

**Comment by MuhammadGagah** [comment]
So far, I've never had a problem with vertual audio on a windows server.
Maybe the Windows server you are using doesn't support vertual audio.
You can contact the DigitalOcean team to inquire about this
