### ISSUE TITLE
TTMediaBot will Fall back to Empty Status With The Mail Gender Set

### ISSUE THREAD

**Issue by lbk2907** [gumerov-amir/TTMediaBot#54]
Hey there! I just download the latest TTMediaBot that was updated yesterday. This update was fix the bug so that when the TeamTalk server restart, it will automatic reconnect. A long with this update, I found 1 bug that is each time the TeamTalk server restart, TTMediaBot will fallback to an empty status with the mail gender set. To fix this problem, either I need to restart TTMediaBot or I play something and stop it. After I do one of the way above, it will back to the status that I said and the mail gender will automaticly removed. If I set the gender to female, this problem also happend. I need to use the same way to fix it. Thanks.

**Comment by a11cf0** [comment]
Fixed in cf4a40cb12a890a4a8.
