### ISSUE TITLE
TTMediaBot not logging in at all but also doesn't give error.

### ISSUE THREAD

**Issue by simteraplications** [gumerov-amir/TTMediaBot#55]
Hi. I have just been trying to set up a tt media bot. I have done it before so i didn't think it would be a problem how ever it turns out that the bot doesn't connect at all to the server but doesn't give any error. What can i do to trace this?

**Comment by a11cf0** [comment]
Please show the log.

**Comment by simteraplications** [comment]
The log only has 2 entries, one off them beeing that vk failed to authenticate but that is ok since i use yt any way, and the second one is tat the bot started.
