### ISSUE TITLE
can type commands in oter channels

### ISSUE THREAD

**Issue by nunotfc** [gumerov-amir/TTMediaBot#59]
hello, it is a error, is there something i'm doing wrong? for example im on oter channel, and can disturb oters doing comands in a bot that are not in my channel.

**Comment by a11cf0** [comment]
You can to this if you are an administrator. All server administrators are automatically bot admins.

**Comment by Marc2p** [comment]
I cannot send commands to the bot while in another channel, even though I am an administrator. I have seen on other servers that when you send a message to the bot in another channel, it responds with a message. In my case, the bot does not respond at all.
I understand that I should run the command if I'm an administrator, and respond with an error if I'm not.
What could be happening?

**Comment by lbk2907** [comment]
Are the user used by the player can see other users in the server?

**Comment by cyrmax** [comment]
@nunotfc @Marc2p Hello.
I am very sorry but i couldn't reproduce your problem on latest source code. 
If the problem still persist please
* Check if you are using latest version of the bot;
* Try to reproduce the problem on latest sources;
* Reopen this issue and send us complete logs along with full detailed description of all steps you are doing.
