### ISSUE TITLE
Bot connects but get a database error if I send commands.

### ISSUE THREAD

**Issue by blindndangerous** [gumerov-amir/TTMediaBot#65]
I've gotten the bot to connect to my server, but if I try to send any commands, I get the following error.
ERROR [2022-04-02 19:48:31,907]: [5] User authorization failed: no access_token passed. in MainThread file: vk.py line 69 function initialize
INFO [2022-04-02 19:48:33,622]: Started in MainThread file: __init__.py line 89 function run
INFO [2022-04-02 19:49:12,572]: New message h from username in MainThread file: __init__.py line 94 function run
ERROR [2022-04-02 19:49:12,572]:  in Thread-4 file: __init__.py line 110 function _run
Traceback (most recent call last):
  File "C:\Users\username\Downloads\git\TTMediaBot\bot\commands\__init__.py", line 95, in _run
    self.ttclient.send_message(
  File "C:\Users\username\Downloads\git\TTMediaBot\bot\TeamTalk\__init__.py", line 156, in send_message
    message = TeamTalkPy.TextMessage()
  File "C:\Users\username\Downloads\git\TTMediaBot\TeamTalkPy\TeamTalk5.py", line 727, in __init__
    assert(DBG_SIZEOF(TTType.TEXTMESSAGE) == ctypes.sizeof(TextMessage))
AssertionError

**Comment by cyrmax** [comment]
@blindndangerous Hello.
As i see in your log, you didn't set access token for VK service so you cannot use VK as a source when searching and playing URLs.
You can get VK access token and save it to your config with vk_auth.py tool in tools directory.

And about the second error in your logs: looks like you are using newer version of TeamTalk sdk than bot supports. You should use TeamTalk sdk version 5.8.x. 
For details about this problem please visit #66.
