### ISSUE TITLE
I can't change bot languaje

### ISSUE THREAD

**Issue by Marc2p** [gumerov-amir/TTMediaBot#76]
I'm trying to change bot languaje, but I can't
Even though I set the language in the config.json file, the bot is still in English. The same thing happens if I try to send the command cl languaje
When I send the command, it says the language has been changed, but it's still English

**Comment by lbk2907** [comment]
What error you get?

**Comment by Marc2p** [comment]
No errors. Here is the log:

> `` ERROR [2022-07-30 18:50:41,491]: [5] User authorization failed: no access_token passed. in MainThread file: vk.py line 7
4 function initialize
INFO [2022-07-30 18:50:42,641]: Started in MainThread file: __init__.py line 90 function run
INFO [2022-07-30 18:50:53,414]: New message cl es from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:50:58,545]: New message sc from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:51:01,987]: New message rs from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:51:02,007]: Bot closed in Thread-6 file: __init__.py line 113 function close
ERROR [2022-07-30 18:51:03,207]: [5] User authorization failed: no access_token passed. in MainThread file: vk.py line 7
4 function initialize
INFO [2022-07-30 18:51:04,385]: Started in MainThread file: __init__.py line 90 function run
INFO [2022-07-30 18:51:08,817]: New message h from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:51:28,191]: New message ua from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:52:02,483]: New message cc from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:52:05,656]: New message h from Markk in MainThread file: __init__.py line 95 function run
INFO [2022-07-30 18:52:24,034]: Bot closed in MainThread file: __init__.py line 113 function close

It just seems to ignore the language setting in the config.json file, staying with English.

The same thing happens when sending the cl command, it says the language has been changed but it remains in English

**Comment by Marc2p** [comment]
I also tried clearing the cache file and clearing the cache with the cc command

**Comment by lbk2907** [comment]
Do you already compile the language file by run the compile_locale.py in
the tools folder?

**Comment by Marc2p** [comment]
Okay, there was the problem. I did not investigate and the documentation does not contain that information, it should be added.

Thank you very much!
