### ISSUE TITLE
Problem running the bot as a service

### ISSUE THREAD

**Issue by Marc2p** [gumerov-amir/TTMediaBot#77]
Hello,
I am trying to run the bot as a service as per the instructions in the attached file.

Running the command systemctl --user start TTMediaBot got the bot to connect to my server and it works fine, but it stops when I log out of the terminal.
I tried to copy the TTMediaBot/systemd/user/ files to /etc/systemd/system/ but when trying to run the bot I get the following error:

> `● TTMediaBot.service - TTMediaBot
     Loaded: loaded (/etc/systemd/system/TTMediaBot.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2022-08-03 21:20:43 EDT; 10min ago
    Process: 7318 ExecStart=/home/ubuntu/ttserver/TTMediaBot/TTMediaBot.sh -c /home/ubuntu/ttserver/TTMediaBot/config.j>
   Main PID: 7318 (code=exited, status=1/FAILURE)
Aug 03 21:20:42 ip-172-31-41-144 systemd[1]: TTMediaBot.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 21:20:42 ip-172-31-41-144 systemd[1]: TTMediaBot.service: Failed with result 'exit-code'.
Aug 03 21:20:43 ip-172-31-41-144 systemd[1]: TTMediaBot.service: Scheduled restart job, restart counter is at 5.
Aug 03 21:20:43 ip-172-31-41-144 systemd[1]: Stopped TTMediaBot.
Aug 03 21:20:43 ip-172-31-41-144 systemd[1]: TTMediaBot.service: Start request repeated too quickly.
Aug 03 21:20:43 ip-172-31-41-144 systemd[1]: TTMediaBot.service: Failed with result 'exit-code'.
Aug 03 21:20:43 ip-172-31-41-144 systemd[1]: Failed to start TTMediaBot.`

What am I wrong?
[Installing Bot on ubuntu 20.txt](https://github.com/gumerov-amir/TTMediaBot/files/9255972/Installing.Bot.on.ubuntu.20.txt)

**Comment by blindgeek** [comment]
You have to allow the user manager to run the service continuously. At least that's what worked for my case.

**Comment by Marc2p** [comment]
Okay, that worked for me too

**Comment by lbk2907** [comment]
Hey there.
Try to run the following command with the root user or the user with sudo privilages.
loginctl enable-linger bot_user
Replace bot_user with your own user.
Hope this helps.
Thanks.
