### ISSUE TITLE
Vaious ishues

### ISSUE THREAD

**Issue by nunotfc** [gumerov-amir/TTMediaBot#90]
hello, i have various ishues
1. Team talk sdk doesnt extracts properly, the teamtalk5.dll is not present instead it downloads a big file, and puts it in a folder, you have to put the dll manually in root folder.
2. mpv.dll downloaded gives error in windows, dinamic link routine load error. 
if you need more information i am available.

**Comment by techexplorers123** [comment]
> hello, i have various ishues
> 1. Team talk sdk doesnt extracts properly, the teamtalk5.dll is not present instead it downloads a big file, and puts it in a folder, you have to put the dll manually in root folder.
> 2. mpv.dll downloaded gives error in windows, dinamic link routine load error. 
> if you need more information i am available.

all of them are fixed now please check
